name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set app version
        id: set_version
        run: echo "::set-output name=appver::$(node -e 'console.log(require("./package.json").version)')"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN_KANBAN_BACKEND }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: halitderya/kanban-backend:${{ steps.set_version.outputs.appver }}-64
          platforms: linux/amd64
          file: ./Dockerfile
          build-args: |
            API_KEY=${{ secrets.API_KEY }}

      - name: Deploying
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker container stop kanban-backend
            docker container rm kanban-backend
            docker rmi $(docker images halitderya/kanban-backend -aq) --force
            docker image pull halitderya/kanban-backend:${{ steps.set_version.outputs.appver }}-64
            docker container run -d --name kanban-backend -p 3002:3000 --network=kanban-backend_mongo-cluster -e API_KEY=${{ secrets.API_KEY }} halitderya/kanban-backend:${{ steps.set_version.outputs.appver }}-64
